### ISSUE TITLE
Bricking m328p on tester

### ISSUE THREAD

**Issue by OperatorB** [lorf/transistortester#1]
Hello!
This command bricks the chip by saying to the chip not to use the 8MHz crystal on board.
And the tester did not displayed anything (before i bricked my suff).
-U lfuse:w:0xff:m

**Comment by lorf** [comment]
I'm sorry for this. This is not due to LFUSE incorrect setting, but due to HFUSE and EFUSE values swapped. I, probably, just copied values from avrdude output, but due to a typo in avrdude source code, they were swapped (see http://svn.savannah.gnu.org/viewvc/avrdude/trunk/avrdude/main.c?r1=1242&r2=1247). Still my fault.
